### ISSUE TITLE
Evaluation on Kitti

### ISSUE THREAD

**Issue by koutilya-pnvr** [sshan-zhao/GASDA#5]
Great work. Thanks for sharing the repo. Did you validate the Kitti dataset on 1-50m or 0-50m while reporting in the paper?

**Comment by koutilya-pnvr** [comment]
Also i couldn't find the evaluation code in this repo. Do you mind sharing it?

**Comment by sshan-zhao** [comment]
Hi,
I have uploaded the test file, but I did not test the code (since I organized the project, the original test code did not work.), because the data was deleted due to the limited space of the server. 
To test the model, you need to do:
1) prepare the data https://github.com/sshan-zhao/GASDA
2) copy the provided models (https://drive.google.com/open?id=1CvuGUTObRhpZpSTYxy-BIRhft6ttMJOP) to GASDA/checkpoints/vkitti2kitti_gasda/, and rename the models 1_* (e.g., 1_net_D_Src.pth)
3) run the command: python test.py --test_datafile 'test.txt' --which_epoch 1 --model gasda --gpu_ids 0 --batchSize 1 --loadSize 192 640  

This is a little bit complex, and I will improve the code to make the test easier (recently I am very busy with my current projects).

**Comment by sshan-zhao** [comment]
> Great work. Thanks for sharing the repo. Did you validate the Kitti dataset on 1-50m or 0-50m while reporting in the paper?

You can find the results in Tab.1 in our paper.

**Comment by koutilya-pnvr** [comment]
Right, I could see the results in that table, but I don't get whats the range of depth values you tested it on. I could see you reported the results on 50m and 80m, but whats the minimum depth value you considered? Is it 0m or 1m? I couldn't find that information in your paper. 

But as per your test code, I could see that you tested your model on the ranges [1e-3, 50m] and [1e-3, 80m]. But just letting you know that the T2Net paper (the work you compared your results with) reported the results on the range [1-50m].
